service:
  port: 80

<#if config.content.variables.petclinic.baseDomain?has_content>
ingress:
  hosts:
    <#assign myUrl = "${config.application.baseUrl}">
    <#if config.application.urlSeparatorHyphen>
    - host: staging-petclinic-helm-${config.content.variables.petclinic.baseDomain}-${myUrl?keep_after("://")}
    <#else>
    - host: staging.petclinic-helm.${config.content.variables.petclinic.baseDomain}.${myUrl?keep_after("://")}
    </#if>
      paths: ['/']
</#if>
